### ISSUE TITLE
Offer options to change the badge type

### ISSUE THREAD

**Issue by julianYaman** [VishwaGauravIn/github-profile-readme-maker#1]
Hello guys,

I really like your tool and used it to create a large part of my README.
I noticed that I can't choose between the different badge styles from [shields.io](https://shields.io/).

It would be useful to be able to switch between the different styles (`plastic`, `flat`, `flat-square`, _for-the-badge`).
As far as I can tell, it seems to be just a parameter in the source URL of each badge (e.g. `style=plastic&logo=appveyor`).

Thanks again for creating this tool. It helped me a lot!

Kind regards,
Julian

**Comment by VishwaGauravIn** [comment]
Thanks Julian for the suggestion,
Option to select badge style is enable in Tech Badges

**Comment by julianYaman** [comment]
Oh, I'm sorry. I didn't see that. I'm sorry I disturbed you.
