### ISSUE TITLE
Hey @VishwaGauravIn , I saw that 2 major badges are missing in the tech stack section, i.e Android and Ios. I have added these two in local and it is working fine. Should I raise a PR. I am attaching a screenshot for your reference.

### ISSUE THREAD

**Issue by AbbyB97** [VishwaGauravIn/github-profile-readme-maker#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VishwaGauravIn** [comment]
Yes, Please raise a PR for that
