### ISSUE TITLE
Adding new Badges for Android and IOS

### ISSUE THREAD

**Issue by AbbyB97** [VishwaGauravIn/github-profile-readme-maker#18]
Hey @VishwaGauravIn , I saw that 2 major badges are missing in the tech stack section, i.e Android and Ios. I have added these two in local and it is working fine. 

Should I raise a PR. I am attaching a screenshot for your reference.

![Screenshot from 2023-03-05 13-48-17](https://user-images.githubusercontent.com/19248801/222949698-51aabc8d-00df-44d8-af8c-c703394f791b.png)

**Comment by VishwaGauravIn** [comment]
Yes, Please raise a PR for the changes

**Comment by AbbyB97** [comment]
Alright thanks for the quick response!

**Comment by AbbyB97** [comment]
I have raised the pr : https://github.com/VishwaGauravIn/github-profile-readme-maker/pull/19
Vercel is asking for authorization please have a look.

**Comment by VishwaGauravIn** [comment]
Merged Successfully, Thanks for contributing 💛
