### ISSUE TITLE
icon design

### ISSUE THREAD

**Issue by weshaan** [VishwaGauravIn/github-profile-readme-maker#21]
i was looking at icons and was wondering if more designs for same tool are possible...like in the image below; like user gets option to change theme of icon design
![image](https://user-images.githubusercontent.com/118920744/224466326-1206f67d-ba40-4425-91dc-d1911e1a639c.png)

**Comment by VishwaGauravIn** [comment]
Hey, We actually use shields.io for badges as of now but we can add more styles if we get a library that contains all the existing tech logos.

**Comment by weshaan** [comment]
ohk got it, idk if this help but check this out : https://github.com/weshaan/github-profile-readme-generator/tree/master/src/images/icons

**Comment by VishwaGauravIn** [comment]
> ohk got it, idk if this help but check this out : . https://github.com/weshaan/github-profile-readme-generator/tree/master/src/images/icons

Sorry for the late reply, I just checked the repo but there are a lot of icons missing so we can't just use that but we will surely think about adding more cool styles (even better) in future.

**Comment by weshaan** [comment]
ohk, cool!
