### ISSUE TITLE
Add Random Memes Not Working

### ISSUE THREAD

**Issue by nassimessaidi** [VishwaGauravIn/github-profile-readme-maker#25]
When attempting to add a random meme, only an empty state is shown, with only the icon of the image appearing, which may be due to the image not being found

**Comment by VishwaGauravIn** [comment]
FIXED
Please regenerate your readme or replace the random meme with ```![random memer](https://rm.up.railway.app/)```

**Comment by nassimessaidi** [comment]
Done, Thanks
