### ISSUE TITLE
Meme Is not Working

### ISSUE THREAD

**Issue by VinaySavla** [VishwaGauravIn/github-profile-readme-maker#29]
**Describe the bug**
A clear and concise description of what the bug is that when i checked the add meme and tried the code it does not show any image or meme. i check the code the api which is used to generate memes i mean the project hosted on railway is shutdown. so it does not generate any meme.

**To Reproduce**
1. Go to website
3. Click on checkbox of add meme
4. generate the code and test
5. See error

**Expected behavior**
meme should have been generated

**Screenshots**
![image](https://github.com/VishwaGauravIn/github-profile-readme-maker/assets/71120627/8e0ead47-2edf-4f7d-a628-c7d7df883210)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows
 - Browser [e.g. chrome, safari]: Chrome/Edge

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: Realme 8
 - OS: [e.g. iOS8.1]: Android 12
 - Browser [e.g. stock browser, safari]: Chrome/Edge

**Comment by VinaySavla** [comment]
i tried clonning you project it has some conflicting dependencies. 
i used --force and ran the project and try some limited free api. they are working perfectly fine. but the thing is they are free for 1000 api requests per month. so i did not created a pull request with that.

**Comment by VishwaGauravIn** [comment]
Yes that issue is there, I am looking for a better alternative. Let me know if you have a better suggestion.

**Comment by VinaySavla** [comment]
i accidently closed it

**Comment by VinaySavla** [comment]
I have created a pull request check that out.

**Comment by VinaySavla** [comment]
Major thing is check for repository conflict. That's also a big issue
