### ISSUE TITLE
Add more socials, for example Mastodon

### ISSUE THREAD

**Issue by tsievert** [VishwaGauravIn/github-profile-readme-maker#33]
**Is your feature request related to a problem? Please describe.**
It would be great if the following socials could be integrated:
- Mastodon
- Researchgate
- ORCiD
- Google scholar

I know most of them are not relevant for tech folks, but more and more researchers are using GitHub to host and share data or code.

**Comment by VishwaGauravIn** [comment]
Hi, Thanks for the feature request. We have added mastodon. Unfortunately, the other 3 are not social media so we won't be able to add them as a social media link and also not widely used but you can still add them manually.
Thanks for GPRM 💛
