### ISSUE TITLE
Add Git and Github

### ISSUE THREAD

**Issue by paragpallavsingh** [VishwaGauravIn/github-profile-readme-maker#34]
This is very interesting project.
I found that Git and Github are two skills that can be added.
It will be a great add-on

**Comment by mukundsolanki** [comment]
@paragpallavsingh  I have added the Git and GitHub Badges

Pull Req: https://github.com/VishwaGauravIn/github-profile-readme-maker/pull/35

@VishwaGauravIn Have a look over this!

**Comment by VishwaGauravIn** [comment]
Thanks @mukundsolanki for your contribution and Thanks @paragpallavsingh for raising this issue 💛
