### ISSUE TITLE
Enhance README Generator with Deno Oak and Fresh Support

### ISSUE THREAD

**Issue by shishiro26** [VishwaGauravIn/github-profile-readme-maker#37]
Problem:
The current README generator fails to incorporate essential information about Denojs, Oak, Fresh for FRAMEWORKS, PLATFORMS & LIBRARIES.

Solution:
Include checkboxes for Deno Oak and Fresh FRAMEWORKS, PLATFORMS & LIBRARIES sections respectively, allowing users to easily showcase these technologies in their readme's. 

I would like to work on this under Hacktoberfest

**Comment by VishwaGauravIn** [comment]
we added approximately 57 new famous tech tools, please check, and thanks for contributing!
