### ISSUE TITLE
"Feature Request: Add Social Links to Generated README"

### ISSUE THREAD

**Issue by PrakharSachan5342** [VishwaGauravIn/github-profile-readme-maker#39]
Add a new feature to the GitHub Profile ReadMe Maker (GPRM) website that allows users to include links to their social media profiles in the generated README.

Details:
Currently, users can create a README for their GitHub profile using GPRM, showcasing their projects and skills. This feature aims to enhance user profiles by providing a way to include links to various social media platforms.

Implementation:
Introduce a new section in the GPRM homepage where users can input their social media handles.
Allow users to enter handles for popular platforms like Twitter, GitHub, LinkedIn, and potentially others.
Modify the code that generates the README in the /api/hello.js file to include the social media links in the generated content.

Expected Behavior:

Users will see a new form on the GPRM homepage to input their social media handles.
The generated README will include links to the user's social media profiles, making it easier for visitors to connect and follow the user on different platforms.

**Comment by VishwaGauravIn** [comment]
This feature is already available, kindly check it by creating a new ReadMe. Let me know if you face any issue.
