### ISSUE TITLE
Excel and Power BI Missing in tech stack

### ISSUE THREAD

**Issue by abhdhar-1618** [VishwaGauravIn/github-profile-readme-maker#41]
Is your feature request related to a problem? Please describe.

I have noticed that the current list of technologies in the tech stack does not include Microsoft Excel and Power BI. As these tools play a significant role in data analysis, reporting, and visualization, their inclusion would provide a more comprehensive overview of the technology stack.

Describe the solution you'd like ?

I would like to propose the addition of Microsoft Excel and Power BI to the list of technologies in the tech stack. Both tools are widely used in the industry for data-related tasks, and acknowledging their presence would be beneficial for users and contributors seeking information about the technology landscape. I have already created a Pull Request and made changes to the "tech.js" file and would be extremely happy if that gets merged with the main branch.

Describe alternatives you've considered ?

I understand that the tech stack may be curated with specific criteria in mind. However, considering the prevalence and relevance of Microsoft Excel and Power BI in various domains, their inclusion aligns with the goal of providing a holistic view of the technologies utilized in the project.

Additional context ?

Adding Microsoft Excel and Power BI to the tech stack would not only enhance the completeness of the list but also acknowledge the importance of these tools in data analysis and visualization workflows. It could be particularly valuable for users who are familiar with or rely on these tools in their projects.

![Power BI](https://github.com/VishwaGauravIn/github-profile-readme-maker/assets/61697483/fd286299-7029-4363-8e0c-8ca23b72e054)
![Excel](https://github.com/VishwaGauravIn/github-profile-readme-maker/assets/61697483/edbae6df-b801-4fd2-a723-a6a92a07450b)

**Comment by VishwaGauravIn** [comment]
added power bi in **others**
