### ISSUE TITLE
Lack of Data Persistence in GPRM

### ISSUE THREAD

**Issue by Anas-Shakeel** [VishwaGauravIn/github-profile-readme-maker#52]
**Bug / Problem**
I noticed a bug (lack of feature) in the GPRM, where the entered data is **not persisted**, causing inconvenience for users. After creating the profile and entering all the data, if we refresh the page or close & reopen the site again, all our entered **data is lost**.

**To Reproduce**
1. Open the **GPRM**.
2. Enter some data into the fields (e.g., bio, projects, social links).
3. **Refresh** the page or close and reopen the browser.
4. Notice that the entered data is not persisted, and **the fields are empty.**

**Expected behavior**
I expected that the data I entered in GPRM would be **saved** (cache/session probably), allowing me to revisit the page later and continue editing or updating my profile **without losing** the entered information.

**Desktop (please complete the following information):**
 - OS: Windows 10 (22H2)
 - Browser Chrome
 - Version 22

**Comment by VishwaGauravIn** [comment]
Hi Anas, thanks for your feedback but actually that's not a bug, it is intended to be in that way only. The data persists only for a session so that you can generate different profile, at different times. But let me know if you want it to persist across sessions, I'll think on that.

**Comment by Anas-Shakeel** [comment]
> Hi Anas, thanks for your feedback but actually that's not a bug, it is intended to be in that way only. The data persists only for a session so that you can generate different profile, at different times. But let me know if you want it to persist across sessions, I'll think on that.

Yes please, ofcourse i want it to persist across sessions. Creating a profile from start to finish takes considerable amount of time, i don't want to write everything again and again when i want/need to update my profile. See if you can do something about it! other generators do persist data but they are not as good as this one!
