### ISSUE TITLE
Feat: Appwrite Icon Option

### ISSUE THREAD

**Issue by Sanchitbajaj02** [VishwaGauravIn/github-profile-readme-maker#53]
**Is your feature request related to a problem? Please describe.**
While creating a profile, I found that there should be a button for Appwrite database as well.

**Additional context**
I searched about the icon but couldn't find one. Please find below the the reference screenshot.

![image](https://github.com/VishwaGauravIn/github-profile-readme-maker/assets/55249639/c54f0b39-60fa-4f74-9ce3-0f31d2f5afef)

> [!NOTE]
> I can contribute to this feature if you like me to work on it 😊

**Comment by VishwaGauravIn** [comment]
It is not widely used as of now, thus not added to the database section but will be added in the future.

For now, you can use this

![Appwrite](https://img.shields.io/badge/Appwrite-black?style=for-the-badge&logo=appwrite&logoColor=pink)

#### Code

```md
![Appwrite](https://img.shields.io/badge/Appwrite-black?style=for-the-badge&logo=appwrite&logoColor=pink)
```

Thanks for contributing 💛
