### ISSUE TITLE
Inconsistent Scroll Issue on mobile devices.

### ISSUE THREAD

**Issue by gdhyani** [VishwaGauravIn/github-profile-readme-maker#57]
**Describe the bug**
When using mobile webpage and filling the first step of about you. If the text overflow then sometimes user can't scroll right or left in the text area.

**To Reproduce**
1. Go to the website on phone.
2. Enter username
3. Click on submit 
4. Now enter something very big in the about you section. Try to enter after mockup text is enabled and add directly to second or third line.
5. Now you can scroll text area. This is the inconsistent.

**Expected behavior**
It should scroll left and right.

**Screenshots**

**Desktop (please complete the following information):**
 - OS : Android
 - Browser : Chrome

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 1
 - OS: Android 14
 - Browser : Chrome
 - Version Latest

**Comment by VishwaGauravIn** [comment]
Can you please attach a video of it? I am unable to replicate this issue on my mobile.

**Comment by gdhyani** [comment]
https://github.com/VishwaGauravIn/github-profile-readme-maker/assets/67196176/bf0c9c8a-d639-4a7f-a20a-05203b456088

**Comment by VishwaGauravIn** [comment]
Checked, it is a mobile-specific issue with textarea which occurs only when the keyboard is open.
