### ISSUE TITLE
App crashes on incorrect Tech input

### ISSUE THREAD

**Issue by kumarAnand05** [VishwaGauravIn/github-profile-readme-maker#59]
**Describe the bug**
Site crashes on entering keywords in search box that are not related to the listed technologies

**To Reproduce**
1. Open website and provide GitHub username
2. Fill about me form, GitHub stats page and social links page to move to tech selection page
3. Enter random keywords that are not related to the listed tech skill (eg. 'Linux')
4. Site crashes and "Application error: a client-side exception has occurred (see the browser console for more information)." message is displayed

**Expected behavior**
It should show no such tech listed message or provide function to add custom tech skill

**Screenshots**
![image](https://github.com/VishwaGauravIn/github-profile-readme-maker/assets/111251492/a10f9628-19ee-4e41-a200-58685fd777bb)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 124.0.6367.201

**Comment by VishwaGauravIn** [comment]
Thanks for reporting, the issue has been resolved.
