### ISSUE TITLE
Missing themes in Top Contributed Repo List.

### ISSUE THREAD

**Issue by Harshh18** [VishwaGauravIn/github-profile-readme-maker#60]
**Describe the bug**
The below listed themes are missing in the top contributed repo list.

- chalk
- alduin
- darkhub
- juicyfresh
- buddhism
- oldie
- onestar
- gitdimmed
- matrix

All these themes contain the same design.

**Comment by VishwaGauravIn** [comment]
Added around 75 themes now, Thanks for contributing 💛
