### ISSUE TITLE
Addition of new tech stack

### ISSUE THREAD

**Issue by neerajmanivarnan** [VishwaGauravIn/github-profile-readme-maker#62]
Need to add a new tech stack into the techstack options.Currently we have spring as an option which is the backend framework for java.Spring-boot is also a framework which is built on top of spring.

I kindly request the maintainers to look into that and assign someone to work on that issue.

**Comment by VishwaGauravIn** [comment]
Springboot is a part of spring, thus you can use spring as badge for both. There is no separate icons thus we can't create separate badges for them.
Thanks for feedback 💛

**Comment by neerajmanivarnan** [comment]
But people who know spring-boot might not know spring.Spring involves a lot of configuration which doesn't really is necessary for spring-boot.It is just like react and javascript.
