### ISSUE TITLE
Top language & Github stat Cards aree not working

### ISSUE THREAD

**Issue by soummyaanon** [VishwaGauravIn/github-profile-readme-maker#63]
**Describe the bug**
Okay Basically The bug Is The Two cards Top Language and Gihub Stat Are not Working Basically They Are not able to fetch the  data from github api may be 

If you click on the card they are showing This  "Error Fetching Resource"
Even on production web site they are not able to fetch the data 

**To Reproduce**
1. Go to https://gprm.itsvg.in
2. Create Your Readme Profile
3. If you Notice the mentioned card are not showing the result
4.  if you are using gprm Just click on your card

**Expected behavior**
They Must FETCH THE DATA as like before they are fecthing 

**Screenshots**
<img width="707" alt="Screenshot 2024-07-18 at 11 44 25 AM" src="https://github.com/user-attachments/assets/816509f7-7c04-4c81-b74a-67588d83ef26">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 15]
 - Browser [ chrome, safari, firefox]

**Comment by VishwaGauravIn** [comment]
The issue has been resolved.
