### ISSUE TITLE
Can't install deps.

### ISSUE THREAD

**Issue by Lohit-pro** [VishwaGauravIn/github-profile-readme-maker#65]
**Is your feature request related to a problem? Please describe.**
I really cant install the dependencies with `npm i`
**Describe the solution you'd like**
Maybe someone please edit the readme file giving info about installing deps.

Thank you.

**Comment by Lohit-pro** [comment]
@VishwaGauravIn

**Comment by VishwaGauravIn** [comment]
it works but if you are facing issues then you can try ```npm I -force```
