### ISSUE TITLE
A new label

### ISSUE THREAD

**Issue by BhJaipal** [VishwaGauravIn/github-profile-readme-maker#66]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm didn't liked it when there was no GTK label in languages and Frameworks list

**Describe the solution you'd like**

For gtk, you can use this one
`![GTK](https://img.shields.io/badge/GTK4-%23000.svg?style=for-the-badge&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAflBMVEVHcEz////9/fn////////58/X//////////////v3k+dfq8fj85OT////1/PD////lAACA6RFzoNF66ABvntBpms78wcipwuKu8HiFrNaP6zra+sHxiIjg6fOg7l3sXl3K3fGaut658o/qOjnH9aXB9Jj719nA1e/0nZz9ubZ/aNOwAAAAEHRSTlMAn8eUC/dnUCqy++nYed1/arU5kQAAAT1JREFUKJFt0tmWgyAMBmDUKtKODhJx37W18/4vOGFxObW55Ds/JJwQcqobdR5uSK6lYB3TsVzZ7QLDKKRM07yUYvB2od5jyBUILMRUyLINjPlDamFHkcrxQRVm7yHdzaLiPMbOfvjsj/KKUrQOIud/w3axRpRxbevO1cj7tpQbSpG392cFAIy4XFe2Sh3Jh7YuEBIsjzCDvGmFitSdlSSpoh0591WkqBJb0AXE2THDyBkLSrwD9cmBU0h+5wPxuamCDZeQRCcspql7FlahvpGgN9Q3r0kNB92SgEGicW6apseGTAJMGO6IbwVbQ3aIBV+GmJDwde7WKkw4sktOeiBytSRML4k/XxGgdsw2uP3ntV3t0m2PWHMgfuIzjs4bGL0tqhD7XF2a6e+rljj4stThK4Pi7n3bd900ox9H/7H0Lf8wiiWvAAAAAElFTkSuQmCC`

![GTK](https://img.shields.io/badge/GTK4-%23000.svg?style=for-the-badge&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAflBMVEVHcEz////9/fn////////58/X//////////////v3k+dfq8fj85OT////1/PD////lAACA6RFzoNF66ABvntBpms78wcipwuKu8HiFrNaP6zra+sHxiIjg6fOg7l3sXl3K3fGaut658o/qOjnH9aXB9Jj719nA1e/0nZz9ubZ/aNOwAAAAEHRSTlMAn8eUC/dnUCqy++nYed1/arU5kQAAAT1JREFUKJFt0tmWgyAMBmDUKtKODhJx37W18/4vOGFxObW55Ds/JJwQcqobdR5uSK6lYB3TsVzZ7QLDKKRM07yUYvB2od5jyBUILMRUyLINjPlDamFHkcrxQRVm7yHdzaLiPMbOfvjsj/KKUrQOIud/w3axRpRxbevO1cj7tpQbSpG392cFAIy4XFe2Sh3Jh7YuEBIsjzCDvGmFitSdlSSpoh0591WkqBJb0AXE2THDyBkLSrwD9cmBU0h+5wPxuamCDZeQRCcspql7FlahvpGgN9Q3r0kNB92SgEGicW6apseGTAJMGO6IbwVbQ3aIBV+GmJDwde7WKkw4sktOeiBytSRML4k/XxGgdsw2uP3ntV3t0m2PWHMgfuIzjs4bGL0tqhD7XF2a6e+rljj4stThK4Pi7n3bd900ox9H/7H0Lf8wiiWvAAAAAElFTkSuQmCC)

**Comment by VishwaGauravIn** [comment]
I add the most used tech and update them periodically. I'm sorry that a part of your tech stack was missing and we will update it in the future, meanwhile, you can add them manually. Thanks for the feedback 💛
