### ISSUE TITLE
The socials can be just above the footer and The most Frequently-asked questions as  important info after making the profie.

### ISSUE THREAD

**Issue by KaranSingh36752** [VishwaGauravIn/github-profile-readme-maker#69]
As when i was using the website and recommend some of my friends i was not able to locate how to enable the ReadMe file to the github profile it self and how to work with it 
So i would recommend to change the Socials sections to bottom and provide the information on how to get on profile details as 
it is below and dont know how to do that so when a person ends with the making the profile provide him this information as pop up or details page : 
this is for what i am taking...
If you already have your personal repository (personal repository name is same as your GitHub username) then you can copy paste the code generated from GPRM in your ReadMe file. If you don't have your personal repository then follow this :
Step 1 : Go to https://github.com/new and enter the same name as your GitHub username into the Repository name field.
Step 2 : Leave the repo as a Public repo (by default).
Step 3 : Also, make sure to initialize it with a README to get started.
Step 4 : Paste the code generated from this website inside your ReadMe file.
Step 5 : Commit the changes to add a ReadMe to your GitHub Account.

**Comment by VishwaGauravIn** [comment]
Thanks for your valuable feedback, I'll add a video regarding this on the website so that it is easy to use, by this weekend.
