### ISSUE TITLE
Addition of Game Development Platforms for badges (Unity, Unreal, Godot, etc.)

### ISSUE THREAD

**Issue by rs0125** [VishwaGauravIn/github-profile-readme-maker#72]
**Is your feature request related to a problem? Please describe.**
I was making my github readme on this platform as a game and XR developer when I realised that Unity wasn't there on the platform (which I had later manually added after going through markdown badge documentation)

This made me realise that the platform currently does not provide badges for some widely-used game development technologies, such as Unity and other related GameDev platforms (e.g., Unreal Engine, Godot). These are essential for developers in the game development space to represent their tech stack accurately on their GitHub profiles.

**Describe the solution you'd like**
Integrate Unity (and other engines) as selectable tech stack badges. Documentation for them is available on https://ileriayo.github.io/markdown-badges/#markdown-badges
![image](https://github.com/user-attachments/assets/fbb323c0-9c0b-47b6-a0b4-f250b52719fc)

**Additional context**
I noticed that other tech stack badges like web frameworks and general-purpose languages are well-covered. Expanding support for GameDev technologies would attract more developers from that community.

If possible you could perhaps assign me the issue and I could just fork and send a PR with it fixed.

**Comment by VishwaGauravIn** [comment]
Hi @rs0125 , Thanks for the feedback. I have added most of the gaming-related tools and platforms now. Thanks for using GPRM 💛
