### ISSUE TITLE
Github Stats

### ISSUE THREAD

**Issue by Mostafizur-Rahman8391** [VishwaGauravIn/github-profile-readme-maker#75]
**Describe the bug**
Github stats not showing all the things and contib count

**Screenshots**
![image](https://github.com/user-attachments/assets/efcc185b-f536-4bf9-b03e-de508e01c67c)

**Comment by VishwaGauravIn** [comment]
![Screenshot_2024-12-04-07-45-08-95_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/1689d5ab-ce1c-4eef-bccb-55263085bcd0)

Change your contribution settings to shows private contributions.
