### ISSUE TITLE
"Donate us" button rename

### ISSUE THREAD

**Issue by palodaman** [VishwaGauravIn/github-profile-readme-maker#76]
**Describe the bug**
the button says "donate us" which implies that a user has the ability to donate yourself. 

**Expected behavior**
Ideally it should be "Donate" or "Donate to us/me"

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Changed the text 'Let People Help You via Donations' to 'Donate to Me' to clarify that the section is about allowing others to donate to the user, addressing the GitHub issue.

You can review changes in this commit: https://github.com/mnmnk43434/VishwaGauravIn-github-profile-readme-maker-76/commit/1f5ad130549907fb51a3cd960504fb4efedaae29.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by VishwaGauravIn** [comment]
Fixed, Thanks for contributing 💛
