### ISSUE TITLE
Error to import github repo to vercel

### ISSUE THREAD

**Issue by Torrente178** [VishwaGauravIn/github-profile-readme-maker#77]
I have created a fork of the project and I wanted to import it to Vercel but when I hit Deploy to finish creating it I get this error (Command “npm install” exited with 1)
![pantallazo](https://github.com/user-attachments/assets/e02695c8-ee1b-4120-9c36-a5fee9f74ec9)

**Comment by VishwaGauravIn** [comment]
Share full screenshot

**Comment by Torrente178** [comment]
![error2](https://github.com/user-attachments/assets/ed49df4e-d2be-4cb7-a2e4-c5a0e73471b6)
![error1](https://github.com/user-attachments/assets/4cbf657d-4e43-4174-b84d-6f9c43eed17c)

**Comment by VishwaGauravIn** [comment]
Use `npm i --force` for installing dependencies
